modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="wings"
version="${version}"
displayName="Wings"
description='''
Adds various wings to Minecraft that allow for creative-like flight
'''

[[dependencies.wings]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.wings]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"